### ISSUE TITLE
adding rcosmo for CRAN Task View: Analysis of Spatial Data 

### ISSUE THREAD

**Issue by olenko** [r-spatial/task_views#12]
As it was advised I added rcosmo to Spatial.ctv and submitted PR to ctv/Spatial.ctv.
________________________________________
From: Roger Bivand [Roger.Bivand@nhh.no]
Sent: Saturday, 24 November 2018 12:20 AM
To: Andriy Olenko
Subject: Re: rcosmo for CRAN Task View: Analysis of Spatial Data

Please enter an issue at https://github.com/r-spatial/task_views<https://protect-au.mimecast.com/s/9exNC1WZ5rt6r82WhYwdVI?domain=github.com>, and
possibly make a PR to ctv/Spatial.ctv.

Roger

On Fri, 23 Nov 2018, Andriy Olenko wrote:

> Dear Professor Bivand
>
> I write to you as the Maintainer of CRAN Task View: Analysis of Spatial Data.
>
> Recently the package rcosmo was uploaded to CRAN: https://cran.r-project.org/web/packages/rcosmo/index.html<https://protect-au.mimecast.com/s/GwcvC2xZ6vCVL7PycMeWKy?domain=cran.r-project.org>
>
> Could you please consider including rcosmo in the Task View: Analysis of Spatial Data.
>
> The package fits the following topics.
>
> - Classes for spatial data: rcosmo provides simple access to spherical and HEALPix data. It extends standard dataframes for HEALPix-type data.
>
> - Handling spatial data: rcosmo offers various tools for geometric transformations, computations, and statistical analysis of spherical data.
>
> - Visualisation: rcosmo provides several tools to interactively visualize HEALPix data, in particular, to plot data in arbitrary spherical windows.
>
> - Geostatistics: rcosmo offers various geostatistics methods for spherical data: descriptive statistics, entropy based methods, covariance-variogram methods, etc. Most of rcosmo features were developed for Cosmic Microwave Background data, but they can also be used for any spherical data.
>
> I am ready to provide more information, if required.
>
> Sincerely yours,
> Andriy Olenko
>
>

--
Roger Bivand
Department of Economics, Norwegian School of Economics,
Helleveien 30, N-5045 Bergen, Norway.
voice: +47 55 95 93 55; e-mail: Roger.Bivand@nhh.no
http://orcid.org/0000-0003-2392-6140<https://protect-au.mimecast.com/s/N7WOC3Q872FXjZ6NCYrGhL?domain=orcid.org>
https://scholar.google.no/citations?user=AWeghB0AAAAJ&hl=en<https://protect-au.mimecast.com/s/qBznC4QZgRFzZrMktNZmBD?domain=scholar.google.no>

**Comment by rsbivand** [comment]
OK, thanks. This will go to the main ctv package and CRAN in a few weeks.
