### ISSUE TITLE
add package cancensus to section specific geospatial data sources of interest

### ISSUE THREAD

**Issue by dshkol** [r-spatial/task_views#14]
The package is [cancensus](https://cran.r-project.org/web/packages/cancensus/) and provides access to Statistics Canada's Census data with the option to retrieve all data as spatial data.

**Comment by rsbivand** [comment]
@dskol in an email to me suggested "Wanted to suggest an addition for a package that I'm the maintainer of for the section "Specific geospatial data sources of interest". " Yesterday, in the #rspatial chat session, there was this: https://twitter.com/llbaker1707/status/1267822025101340674. @Nowosad  and others - maybe this is worth a push?

**Comment by Nowosad** [comment]
Hi @rsbivand, what is worth a push? I think I do not understand your question...

**Comment by rsbivand** [comment]
Sorry for brevity. As I read the tweet, I thought that the task view section might be revisited to give a little more guidance and detail on data sources, possibly re-ordering? Some are API to online, some are static files, etc. Maybe Laurie Baker could be drawn in, at least to review a draft revision?

**Comment by rsbivand** [comment]
@dshkol does https://github.com/r-spatial/task_views/commit/6a1076120d34fa62b042865a46203be840779483 make the minimal change needed?

**Comment by dshkol** [comment]
Yes, thanks for adding @rsbivand.
