### ISSUE TITLE
Detail how {terra} is deigned to replace {raster}

### ISSUE THREAD

**Issue by charliejhadley** [r-spatial/task_views#17]
I've been [asked by Roger Bivand](https://twitter.com/RogerBivand/status/1349712475374178304?s=20) to raise an issue that {terra} is not currently mentioned on the Spatial Task View.

It would be beneficial for the task view to mention that {terra} is designed to replace {raster}.

**Comment by rsbivand** [comment]
Committed to **ctv** SVN, will update on CRAN in due course.
