### ISSUE TITLE
rgee package

### ISSUE THREAD

**Issue by myoung3** [r-spatial/task_views#18]
I was scrolling through the spatial task view recently and noticed that `rgee` wasn't listed. This is R's (only?) interface to Google Earth Engine and thus it seems like it should be included (under "Interfaces to Spatial Web-Services")

**Comment by rsbivand** [comment]
Please provide a sentence to add - all this takes time, so offering a sentence makes it easier to handle.

**Comment by myoung3** [comment]
`rgee` provides an API to Google Earth Engine, which is a cloud-based catalogue of remote sensing data and a gis system for processing spatial data.
