### ISSUE TITLE
Task views migrating to md/Rmd

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/task_views#23]
This repo will be archived when the steps outlined in:

[CRAN_task_views_email_211217.pdf](https://github.com/r-spatial/task_views/files/7735654/CRAN_task_views_email_211217.pdf)

are completed. May I request that we form a task view team to declare on first appearance on the new, centralized repo? @Nowosad could you join/coordinate the team for `Spatial`? Who could join for `SpatioTemporal` with @edzer?

**Comment by Nowosad** [comment]
Hi @rsbivand -- yes I can join (or if needed - coordinate) the `Spatial` team.

**Comment by rsbivand** [comment]
Good, thanks! May I pass your github handle to Achim?

**Comment by Nowosad** [comment]
Yes.
