### ISSUE TITLE
Archive repository

### ISSUE THREAD

**Issue by kadyb** [r-spatial/task_views#25]
Can we archive this repository on GitHub and eventually update the README with forwarding to https://github.com/cran-task-views/Spatial/?

**Comment by rsbivand** [comment]
Yes, but note that Spatial and SpatioTemporal need referencing.

**Comment by kadyb** [comment]
Should I prepare PR with a rewritten README?

**Comment by rsbivand** [comment]
Yes, please!

**Comment by rsbivand** [comment]
@kadyb  Thanks! Can you execute the archiving of the repo?

**Comment by kadyb** [comment]
Unfortunately not. I think only the repository owner can do this. Please see this: https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#archiving-a-repository

It might also be worth changing the description of the repository in the About section by adding `(archived)` note.

**Comment by rsbivand** [comment]
Ok, will follow up, thanks.
