### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/task_views#4]
Dear @rsbivand,
last week I started making some edits to the Spatial.ctv file, but after some time I've noticed that a version on GitHub is different (older?) than the one at https://cran.r-project.org/web/views/Spatial.html. 
Therefore my question is - how to contribute here? Should I still edit the Spatial.ctv file and make a pull request or is there a better way to proceed?

**Comment by rsbivand** [comment]
The SVN version gets a publication date on appearance, and may also be edited manually or automatcally (the latter when packages get archived on CRAN, I think). I've svn update my svn repo, and copied across that version to the github repo and pushed it.

**Comment by Nowosad** [comment]
Thanks for the explanation @rsbivand. I've made a pull request (https://github.com/r-spatial/task_views/pull/6).

**Comment by rsbivand** [comment]
Thanks; I first merged, but later reverted the PR.

I see:

```
> ctv::read.ctv("Spatial.ctv")
Opening and ending tag mismatch: li line 238 and ul
Opening and ending tag mismatch: ul line 674 and li
Error: 1: Opening and ending tag mismatch: li line 238 and ul
2: Opening and ending tag mismatch: ul line 674 and li
```

when trying to run `ctv2html(read.ctv("Spatial.ctv"))`. Could you please take a look?

**Comment by Nowosad** [comment]
It should be fine now (https://github.com/r-spatial/task_views/pull/8). I've also added an instruction on how to test the changes in the readme file.

@rsbivand, what do you think about adding a link to the Geocomputation with R to the task view? Is it a good idea or it is not?

**Comment by rsbivand** [comment]
Thanks; I switched **inlmisc** for archived **Grid2Polygons** after using `ctv::check_ctv_packages()`, and updated the readme to match.

I don't think adding books etc. is sensible, unless we go for complete coverage, or at least try to include most books. We might do something similar with JSS and RJ articles, so similar if OA. A small PR with relevant books and where to get their code might be worth examining.

On R-Forge ctv as revision 3123.
